### ISSUE TITLE
Great Idea. Curious how your managing versions of files.

### ISSUE THREAD

**Issue by dougcooper** [OutsourcedGuru/OctoPrint-GitFiles#5]
Looking forward to trying this out. Obviously we cant tag files with versions. Are you just creating tags with the filename as part of your workflow?

**Comment by OutsourcedGuru** [comment]
That depends. We could be talking about gcode files or the source code involved with this plugin.

If we're talking about gcode files and managing what makes it to your printer(s), then technically, you would no longer need to decorate your print files' filenames with version information.

## Before this plugin
In the past if you were running a printer farm or other controlled space which manufactures parts, the usual workflow would be to decorate the filenames.

```
# This might be Model 12345, v1.6
M12345_1-6.gcode
```

But then the burden would be on the person running the printer to look up the latest version of that model from a table somewhere. If it's not the latest, then they would need to fetch it, update this printer and then start the job.

## Now, with this plugin
You shouldn't need to do this anywhere, decorating filenames with version information. You might still need to decorate the filename with material selection. My suggestion in the README.md was to segregate by material type under subfolders and then you won't have to do that. See my little sample [repository](https://github.com/OutsourcedGuru/3d-files) for this subfolder behavior.

The new activity would be to press the Github icon button first, let it do a `git pull`, select the file and you'd know that you have the latest version which is checked in.

---

If you wanted to use tags with your gcode files, the push behavior then looks slightly different:

```
git add .
git tag 1.6
git commit -m "v1.6 Updated M12345"
git push --tags
```

**Comment by dougcooper** [comment]
Thanks for the detailed explanation. The use case description definitely helps. Might I suggest a future feature: multiple github repo support.

**Comment by OutsourcedGuru** [comment]
Oh... very good. I hadn't thought of that.
