### ISSUE TITLE
Doesn't play well with analysis plugins

### ISSUE THREAD

**Issue by OutsourcedGuru** [OutsourcedGuru/OctoPrint-GitFiles#6]
This is the local issue that's related to [another](https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/119) over on the `eyal0/OctoPrint-PrintTimeGenius repository`.

---

> Ruko2010
> OctoPrint Version: 0.16.0
> PrintTimeGenius Version (if you know): 1.3 (I think)
> What did you try: Uploaded files _not_ using the file Upload by octoprint.
> What happened: Of cause, no analysation of my files.
> What did you expect to happen: Time analyzation of my uploaded files.
> Feature Request:
> I'm using the Gitfiles Plugin to transfer the gcode files to my octopi, and of cause, they are not analysed, because they were not uploaded with the octoprint upload dialog. My request is now to have a button "Analyse All", which analyses all gcode-files in the current folder that has not been analysed so far. Is it possible to implement such a feature?

---

> eyal0
> Gitfiles isn't properly updating files.
>
> "uploads" is the folder where all the gcode files are put. But users aren't supposed to copy stuff directly into there. The right way to do it is to put files into the "watched" folder. OctoPrint monitors that folder and moves stuff from there into uploads.
> 
> Because Gitfiles is putting the files into uploads by itself, OctoPrint isn't quite finding out about it properly so PTG isn't getting the list. If @OutsourcedGuru wanted to repair this, maybe it would work to have git fetch all the gcode into a temporary directory and then compare that directory with the contents of the "uploads" directory. For all files that are not matching, copy them from the temporary directory into the "watched" directory. Then let OctoPrint find the files and process them correctly.
> 
> I think that this would solve the problem. Maybe it would be possible to do it without a temporary directory, too, by just comparing file hashes. Up to Gitfiles to figure this out.

---

**Comment by Ruko2010** [comment]
Thanks for having a look at it!

**Comment by OutsourcedGuru** [comment]
I can confirm that analysis doesn't occur naturally when a `git pull` drops files under the `~/.octoprint/uploads` folder system as seen here with both PTG and GitFiles together, noting the missing stars next to each name.

![screen shot 2019-02-23 at 2 53 57 pm](https://user-images.githubusercontent.com/15971213/53292679-f35ce500-377a-11e9-9c6b-42d2c77707fa.png)

**Comment by Ruko2010** [comment]
I just want to admit, that my gitfiles pull in the folder ~/.octoprint/uploads/gitfiles to use both, git and upload files without problems

**Comment by Ruko2010** [comment]
setting watched folder to ~/.octoprint/uploads/gitfiles and cloning the repo into this folder solves the problem.

**Comment by OutsourcedGuru** [comment]
Glad to hear it. As I was exercising everything with mine and a fork of PTG running at the same time, this idea came to me as a workable solution without adding any coding otherwise.
👍
